<a href="https://colab.research.google.com/github/kiar24/datasci_223/blob/Final-Project/Copy_of_FinalProject223.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.geeksforgeeks.org/how-to-import-kaggle-datasets-directly-into-google-colab/
#download opendatasets to download kaggle dataset, pandas as well
#On kaggle account - go to settings, scroll down click new API token, and download kaggle.json - open it up and store username and password
%pip install opendatasets
%pip install pandas PIL numpy scikit-learn
import opendatasets as od
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, StratifiedKFold, ParameterGrid, KFold



 #the following dataset is used - download if not working to see, but when you run download provide username and password from kaggle.json earlier
od.download(
    "https://www.kaggle.com/datasets/prashant268/chest-xray-covid19-pneumonia")

ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL
Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: krishrai707
Your Kaggle Key: ··········


100%|██████████| 2.06G/2.06G [00:26<00:00, 83.8MB/s]


In [ ]:
#Add other kaggle files here if you want to download.
od.download(
    "https://www.kaggle.com/datasets/tapakah68/facial-emotion-recognition")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: krishrai707
Your Kaggle Key: ··········


100%|██████████| 433M/433M [00:04<00:00, 103MB/s]


In [ ]:
#import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
#train_datagen = ImageDataGenerator(
 #   rescale=1./255,
  #  validation_split=0.2,  # set the validation split
    # add any other data augmentation options you want here
#)

In [ ]:
import os
from PIL import Image
import numpy as np
import pandas as pd

def load_image(image_path):
    with Image.open(image_path) as img:
        img = img.resize((28, 28))
        return np.array(img).flatten()

# Initialize lists to store image data and labels
images = []
labels = []

# Traverse directories
for participant in os.listdir('facial-emotion-recognition/images'):
    participant_path = os.path.join('facial-emotion-recognition/images', participant)
    if os.path.isdir(participant_path):
      for image in os.listdir(participant_path):
        image_path = os.path.join(participant_path, image)
        if os.path.isfile(image_path):
                # Load image and append to images list
          image_data = load_image(image_path)
          images.append(image_data)
 # Extract emotion from image name and append to labels list
    # Assuming the format is 'emotion_image.jpg'
          emotion = image.split('.')[0]
          labels.append(emotion)


In [ ]:
print(labels)
print(images)


['Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger', 'Sad', 'Contempt', 'Happy', 'Disgust', 'Fear', 'Surprised', 'Neutral', 'Anger'

In [ ]:
# Create DataFrame for training data
train_image = pd.DataFrame()
train_image['label'] = labels
train_image['image'] = images

In [ ]:
train_image


label                                              image
0         Fear  [223, 202, 182, 221, 199, 176, 220, 197, 173, ...
1    Surprised  [216, 194, 171, 217, 194, 171, 218, 196, 172, ...
2      Neutral  [213, 188, 165, 214, 189, 165, 213, 189, 164, ...
3        Anger  [225, 202, 177, 225, 202, 176, 225, 202, 177, ...
4          Sad  [228, 207, 183, 226, 203, 177, 225, 201, 174, ...
..         ...                                                ...
147      Anger  [195, 193, 191, 198, 195, 193, 199, 196, 194, ...
148        Sad  [164, 160, 156, 167, 163, 159, 174, 169, 165, ...
149   Contempt  [189, 185, 182, 194, 189, 186, 195, 190, 188, ...
150      Happy  [195, 192, 189, 196, 192, 189, 197, 193, 190, ...
151    Disgust  [190, 187, 185, 194, 190, 188, 196, 193, 190, ...

[152 rows x 2 columns]

In [ ]:
#Mapping is used to assign the emotions (from column in train_image) to either positive or negative emotion
emotion_binarymapping = {
    'Happy': 'Positive',
    'Surprised': 'Positive',
    'Neutral': 'Positive',
    'Anger': 'Negative',
    'Disgust': 'Negative',
    'Fear': 'Negative',
    'Sad': 'Negative',
    'Contempt': 'Negative'
}

#Make a new column - where the label column is mapped as above to positive or negative
train_image['emotion_binary'] = train_image['label'].map(emotion_binarymapping)

In [ ]:
train_image['emotion_binary']

0      Negative
1      Positive
2      Positive
3      Negative
4      Negative
         ...   
147    Negative
148    Negative
149    Negative
150    Positive
151    Negative
Name: emotion_binary, Length: 152, dtype: object

In [ ]:
from re import X
import sklearn.model_selection

X = np.array(train_image['image'].tolist())
Y = np.array(train_image['emotion_binary'].tolist())

Input_train, Input_test, Output_train, Output_test = train_test_split(X,Y, test_size=0.2, random_state=25)

In [ ]:
Output_train = np.array([1 if label == 'Positive' else 0 for label in Output_train])
Output_train

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Reshape

input_size = 2352  # images are 28x28
hidden_size = 24  # Tunable parameter for the hidden layer
num_classes = 1

NN_model = Sequential([
    Dense(8, activation='relu', input_shape=(input_size,)),
    Dense(hidden_size, activation='relu'),
    Dense(hidden_size, activation='relu'),
    Dense(num_classes, activation='sigmoid')
])

NN_model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

NN_model.fit(Input_train, Output_train, batch_size=61, epochs=30)

Epoch 1/30
2/2 [==============================] - 1s 13ms/step - loss: 26.3538 - accuracy: 0.3802
Epoch 2/30
2/2 [==============================] - 0s 9ms/step - loss: 4.3747 - accuracy: 0.4793
Epoch 3/30
2/2 [==============================] - 0s 8ms/step - loss: 0.6915 - accuracy: 0.6198
Epoch 4/30
2/2 [==============================] - 0s 9ms/step - loss: 0.6908 - accuracy: 0.6198
Epoch 5/30
2/2 [==============================] - 0s 10ms/step - loss: 0.6900 - accuracy: 0.6198
Epoch 6/30
2/2 [==============================] - 0s 8ms/step - loss: 0.6892 - accuracy: 0.6198
Epoch 7/30
2/2 [==============================] - 0s 9ms/step - loss: 0.6886 - accuracy: 0.6198
Epoch 8/30
2/2 [==============================] - 0s 9ms/step - loss: 0.6879 - accuracy: 0.6198
Epoch 9/30
2/2 [==============================] - 0s 8ms/step - loss: 0.6873 - accuracy: 0.6198
Epoch 10/30
2/2 [==============================] - 0s 10ms/step - loss: 0.6866 - accuracy: 0.6198
Epoch 11/30
2/2 [==================

#Test set

In [ ]:
Output_test = np.array([1 if label == 'Positive' else 0 for label in Output_test])
Output_test

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0])

In [ ]:
#Model evaluation - validation set

test_loss, test_accuracy = NN_model.evaluate(Input_test, Output_test)
print(f"Validation loss: {test_loss:.2f}")
print(f"Validation accuracy: {test_accuracy:.2f}")

predictimage = NN_model.predict(Input_test)
print(predictimage)

1/1 [==============================] - 0s 280ms/step - loss: 0.6698 - accuracy: 0.6452
Validation loss: 0.67
Validation accuracy: 0.65
1/1 [==============================] - 0s 172ms/step
[[0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]
 [0.4519511]]


#Example images with Output from Testing Data

In [ ]:
import matploblib.pyplot

# Select the first three images and their predicted labels
exampleimage = Input_test[:3]
predicted_labels = np.argmax(predictions, axis=1)[:3]

# Display each image with its predicted label
for i in range(3):
    plt.figure(i)
    plt.imshow(exampleimage[i], cmap='gray')  # remove ', cmap='gray'' if your images are not grayscale
    plt.title(f'Predicted label: {predicted_labels[i]}')
    plt.show()

# krish can you see this


ModuleNotFoundError: No module named 'matploblib'

#Examples of Bad Data that could be messing up the model

#Ignore below for now

In [ ]:
train_generator = train_datagen.flow_from_directory(
    'facial-emotion-recognition',  # replace with the path to your data directory
    target_size=(150, 150),  # replace with the desired image size
    batch_size=32,
    class_mode='binary',  # or 'binary' if you have only two classes
    subset='training',  # specify this is the training set
)

validation_generator = train_datagen.flow_from_directory(
    'facial-emotion-recognition',  # replace with the path to your data directory
    target_size=(150, 150),  # replace with the desired image size
    batch_size=32,
    class_mode='binary',  # or 'binary' if you have only two classes
    subset='validation',  # specify this is the validation set
)

In [ ]:
!ls
train_datagen.samples
validation_generator.samples